services:
  - type: web
    name: ms-informatics-courseware
    runtime: node
    plan: free
    region: singapore
    branch: main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: NODE_VERSION
        value: "22"
